<?php

namespace App\Livewire;

use Http;
use Livewire\Attributes\Layout;
use Livewire\Component;

class ItunesAdvanced extends Component
{
    public $countryCode = 'be';
    public $resultLimit = 10;
    public $showAlbums = true;
    public $loading = 'Please wait...';

    public $countries = [
        'dz' => 'Algeria',
        'ao' => 'Angola',
        'ai' => 'Anguilla',
        'ag' => 'Antigua and Barbuda',
        'ar' => 'Argentina',
        'am' => 'Armenia',
        'au' => 'Australia',
        'at' => 'Austria',
        'az' => 'Azerbaijan',
        'bs' => 'Bahamas',
        'bh' => 'Bahrain',
        'bb' => 'Barbados',
        'by' => 'Belarus',
        'be' => 'Belgium',
        'bz' => 'Belize',
        'bj' => 'Benin',
        'bm' => 'Bermuda',
        'bt' => 'Bhutan',
        'bo' => 'Bolivia',
        'ba' => 'Bosnia and Herzegovina',
        'bw' => 'Botswana',
        'br' => 'Brazil',
        'vg' => 'British Virgin Islands',
        'bg' => 'Bulgaria',
        'kh' => 'Cambodia',
        'cm' => 'Cameroon',
        'ca' => 'Canada',
        'cv' => 'Cape Verde',
        'ky' => 'Cayman Islands',
        'td' => 'Chad',
        'cl' => 'Chile',
        'cn' => 'China mainland',
        'co' => 'Colombia',
        'cr' => 'Costa Rica',
        'hr' => 'Croatia',
        'cy' => 'Cyprus',
        'cz' => 'Czech Republic',
        'ci' => 'Côte d\'Ivoire',
        'cd' => 'Democratic Republic of the Congo',
        'dk' => 'Denmark',
        'dm' => 'Dominica',
        'do' => 'Dominican Republic',
        'ec' => 'Ecuador',
        'eg' => 'Egypt',
        'sv' => 'El Salvador',
        'ee' => 'Estonia',
        'sz' => 'Eswatini',
        'fj' => 'Fiji',
        'fi' => 'Finland',
        'fr' => 'France',
        'ga' => 'Gabon',
        'gm' => 'Gambia',
        'ge' => 'Georgia',
        'de' => 'Germany',
        'gh' => 'Ghana',
        'gr' => 'Greece',
        'gd' => 'Grenada',
        'gt' => 'Guatemala',
        'gw' => 'Guinea-Bissau',
        'gy' => 'Guyana',
        'hn' => 'Honduras',
        'hk' => 'Hong Kong',
        'hu' => 'Hungary',
        'is' => 'Iceland',
        'in' => 'India',
        'id' => 'Indonesia',
        'iq' => 'Iraq',
        'ie' => 'Ireland',
        'il' => 'Israel',
        'it' => 'Italy',
        'jm' => 'Jamaica',
        'jp' => 'Japan',
        'jo' => 'Jordan',
        'kz' => 'Kazakhstan',
        'ke' => 'Kenya',
        'kr' => 'Korea, Republic of',
        'xk' => 'Kosovo',
        'kw' => 'Kuwait',
        'kg' => 'Kyrgyzstan',
        'la' => 'Lao People\'s Democratic Republic',
        'lv' => 'Latvia',
        'lb' => 'Lebanon',
        'lr' => 'Liberia',
        'ly' => 'Libya',
        'lt' => 'Lithuania',
        'lu' => 'Luxembourg',
        'mo' => 'Macao',
        'mg' => 'Madagascar',
        'mw' => 'Malawi',
        'my' => 'Malaysia',
        'mv' => 'Maldives',
        'ml' => 'Mali',
        'mt' => 'Malta',
        'mr' => 'Mauritania',
        'mu' => 'Mauritius',
        'mx' => 'Mexico',
        'fm' => 'Micronesia, Federated States of',
        'md' => 'Moldova',
        'mn' => 'Mongolia',
        'me' => 'Montenegro',
        'ms' => 'Montserrat',
        'ma' => 'Morocco',
        'mz' => 'Mozambique',
        'mm' => 'Myanmar',
        'na' => 'Namibia',
        'np' => 'Nepal',
        'nl' => 'Netherlands',
        'nz' => 'New Zealand',
        'ni' => 'Nicaragua',
        'ne' => 'Niger',
        'ng' => 'Nigeria',
        'mk' => 'North Macedonia',
        'no' => 'Norway',
        'om' => 'Oman',
        'pa' => 'Panama',
        'pg' => 'Papua New Guinea',
        'py' => 'Paraguay',
        'pe' => 'Peru',
        'ph' => 'Philippines',
        'pl' => 'Poland',
        'pt' => 'Portugal',
        'qa' => 'Qatar',
        'cg' => 'Republic of the Congo',
        'ro' => 'Romania',
        'ru' => 'Russia',
        'rw' => 'Rwanda',
        'sa' => 'Saudi Arabia',
        'sn' => 'Senegal',
        'rs' => 'Serbia',
        'sc' => 'Seychelles',
        'sl' => 'Sierra Leone',
        'sg' => 'Singapore',
        'sk' => 'Slovakia',
        'si' => 'Slovenia',
        'sb' => 'Solomon Islands',
        'za' => 'South Africa',
        'es' => 'Spain',
        'lk' => 'Sri Lanka',
        'kn' => 'St. Kitts and Nevis',
        'lc' => 'St. Lucia',
        'vc' => 'St. Vincent and The Grenadines',
        'sr' => 'Suriname',
        'se' => 'Sweden',
        'ch' => 'Switzerland',
        'tw' => 'Taiwan',
        'tj' => 'Tajikistan',
        'tz' => 'Tanzania',
        'th' => 'Thailand',
        'to' => 'Tonga',
        'tt' => 'Trinidad and Tobago',
        'tn' => 'Tunisia',
        'tm' => 'Turkmenistan',
        'tc' => 'Turks and Caicos',
        'tr' => 'Türkiye',
        'ae' => 'UAE',
        'ug' => 'Uganda',
        'ua' => 'Ukraine',
        'gb' => 'United Kingdom',
        'us' => 'United States',
        'uy' => 'Uruguay',
        'uz' => 'Uzbekistan',
        'vu' => 'Vanuatu',
        've' => 'Venezuela',
        'vn' => 'Vietnam',
        'ye' => 'Yemen',
        'zm' => 'Zambia',
        'zw' => 'Zimbabwe',
    ];

    #[Layout('layouts.vinylshop',
        [
            'title' => 'iTunes - Advanced',
            'description' => 'iTunes - Advanced'
        ])]
    public function render()
    {
        $feed = $this->getFeed();

        return view('livewire.itunes-advanced', compact('feed'));
    }

    public function getFeed()
    {
        $url = "https://rss.applemarketingtools.com/api/v2/{$this->countryCode}/music/most-played/{$this->resultLimit}/"
            . ($this->showAlbums ? 'albums' : 'songs') . ".json";
        $response = Http::get($url)->json();
        // dump($response['feed']);
        return $response['feed'];
    }
}
